name: Deploy Next.js site to Vercel when issues change

on:
  push:
    branches: ["main"]

  issues:
    types: ["opened", "edited", "deleted", "labeled", "unlabeled"]

concurrency:
  group: "vercel"
  cancel-in-progress: true

jobs:
  trigger_deploy:
    if: contains(github.event.issue.labels.*.name, 'publish')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.VERCEL_DEPLOY_URL }}
          method: "POST"
